UnchartedBull/OctoDash

- src/app/control/control.component.scss
- src/app/files/files.component.scss
- src/app/notification/notification.component.scss
- src/styles.scss
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/unchartedbull/octodash/issues).
> Apply fixes from CodeFactor

- src/app/files.service.ts
- src/app/main-screen/main-screen.component.html
- src/app/octoprint-api/filesAPI.ts
- src/app/octoprint-api/jobAPI.ts
- src/app/octoprint-api/printerStatusAPI.ts
This issue has been resolved, it was due to multiple materials being used (not including tool0), as well as a bug in the code that tried to access GCodeAnalysis for non GCode Files.
The displayed filament amount is now the combined amount of all materials used.
Closes #210.
> Fixed multi material issue

- src/app/files/files.component.ts
- src/assets/reset.css
> Fix outline on long press

- src/app/bottom-bar/bottom-bar.component.html
- src/app/bottom-bar/bottom-bar.component.ts
- src/app/files/files.component.ts
- src/app/main-menu/main-menu.component.ts
- src/app/notification/notification.component.scss
- src/app/plugin-service/enclosure.service.ts
> Use correct temperature unit

- main.js
- sample.config.json
- src/app/app.service.ts
- src/app/config/config.service.ts
- src/app/config/no-config/no-config.component.html
- src/app/config/no-config/no-config.component.scss
- src/app/config/no-config/no-config.component.ts
- src/app/job.service.ts
- src/app/main-menu/main-menu.component.ts
- src/app/main-screen/main-screen.component.html
- src/app/notification/notification.component.scss
- src/app/notification/notification.service.ts
- src/app/plugin-service/layer-progress.service.ts
- src/app/printer.service.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/settings/settings.component.ts
- src/app/standby/standby.component.ts
- src/styles.scss
> Finalize Settings menu

- src/app/app.service.ts
- src/app/config/config.old.ts
Custom Actions won't get merged though ...
> Merge as much as possible from old to new config

- package-lock.json
- src/app/files.service.ts
- src/app/files/files.component.html
In reference to #170, I have hacked together a quick fix for file preview when used in conjunction with my UltimakerFormatPackage plugin.
> Adds thumbnail preview for UltimakerFormatPackage plugin support

- src/app/job-status/job-status.component.html
- src/app/job.service.ts
- src/app/layer-progress/layer-progress.component.html
When printing from SD, a thumbnail image should not be retrieved as the filename does not exist in OctoPrint.
Null values should be propagated through to the view instead of replaced with 0. This way values which are not available when printing from SD (listed below, or any other situation also resulting in it being null) can be hidden.
- Filament used
- Time remaining, until OctoPrint has estimated a time remaining based on current print progress, otherwise it shows 0 remaining for the first minute or so of printing, which looks odd
- Layer progress, which shows as layer 0 of 0
Fixes #541
> Fix errors and unnecessary data shown when printing from SD

- README.md
- src/app/job-status/job-status.component.html
- src/app/job-status/job-status.component.scss
- src/app/job-status/job-status.component.ts
- src/app/job.service.ts
- src/app/print-control/print-control.component.scss
- src/app/print-control/print-control.component.ts
This while show the thumbnail of the current print if you click on the percentage. The choice should be remembered until a restart of OctoDash happens.
Demo:
> Show preview while printing (click on percentage)

- src/app/plugin-service/enclosure.service.ts
- src/app/standby/standby.component.ts
Needs testing from issue owner.
Fixes #559.
> Properly handle Connection Errors

- src/app/print-control/print-control.component.ts
> Remember Feed- and Flow-Rate

- README.md
- src/app/printer-status/printer-status.component.html
- src/app/printer-status/printer-status.component.ts
Thanks to @RC-Thoughts for this.
Closes #610
> Reset temperature and fan values more easy

- src/app/control/control.component.ts
- src/app/octoprint-api/printerProfileAPI.ts
- src/app/printerprofile.service.ts
I went ahead and took a stab at fixing the issue where the OctoPrint axis inversion setting was not being respected in the in the printer control view.
- Created PrinterProfileService
- Implemented getDefaultPrinterProfile()
- When Control view loads it gets the default printer profile, and subsequent axis moves take the "inverted" setting into account
Fixes #849.
> Fix issue #849; Respect the OctoPrint axis invert flags

- src/app/files.service.ts
If nothing is returned from the API within 6s an error will be shown. While this is not optimal it should work for now. Fixes #698.
> Add timeout while loading files

- themes/NOX/custom-styles.css
Filament screen corrected with the following changes:
* Filament tr background colour changed to match theme.
* Filament table background gradient removed.
* Filament tr width adjusted to match files section, this also lined up
the scroll bar with its background.
* Filament name width reduced to prevent filament weight being 
run off the screen.
> fix/Updated filament in NOX theme.

- src/app/job-status/job-status.component.html
- src/app/job.service.ts
- src/app/print-control/print-control.component.ts
> Show pause screen if not paused from OctoDash

- src/app/control/control.component.ts
- src/app/plugin-service/enclosure.service.ts
- src/app/plugin-service/filament-manager.service.ts
> add custom action for LED Strip

- src/app/app.service.ts
- src/app/files.service.ts
- src/app/job.service.ts
- src/app/plugin-service/enclosure.service.ts
> Calculate filament weight based on length

- helper/listener.js
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.service.ts
- src/app/config/no-config/no-config.component.ts
- src/app/notification/notification.component.html
- src/app/notification/notification.component.scss
- src/app/notification/notification.component.ts
- src/app/notification/notification.service.ts
- src/app/octoprint-script.service.ts
- src/app/settings/settings.component.ts
- src/app/standby/standby.component.html
> Better connection handling

- themes/theGarbz/Focus/README.md
- themes/theGarbz/Focus/custom-styles.css
Width was slightly too wide so the weight remaining
was not being displayed correcty. Also updated version info.
> Focus Theme: Fixed Filament selector screen

- src/app/app.component.ts
- src/app/app.service.ts
- src/app/config/config.default.ts
- src/app/config/config.model.ts
- src/app/config/config.schema.ts
- src/app/config/config.service.ts
- src/app/config/setup/plugins/plugins.component.html
- src/app/config/setup/plugins/plugins.component.ts
- src/app/config/setup/setup.component.html
- src/app/control/control.component.ts
- src/app/plugin-service/tplink-smartplug.service.ts
- src/app/settings/settings.component.html
- src/app/standby/standby.component.ts
Add the support for TP Link as alternative of PSU Controler plugin (and fix the issue #1244).
It implements 2 custom actions (`[!TPLINKOFF]` and `[!TPLINKON]`) and an option to power on the smartplug when the standby mode exits. I tested these changes on my RPi 3B (and on my laptop) and it seems working without any issues (this is barely a copy/paste of the PSU plugin, without the toggle feature).
Unfortunately, we need a keyboard to setup the IP address in the settings menu (or edit the `config.json` file).
Closes #1244
> Add support for TPLinkSmartPlug plugin

- src/app/config/config.default.ts
- src/app/config/config.model.ts
- src/app/config/config.schema.ts
- src/app/config/config.service.ts
- src/app/filament/change-filament/change-filament.component.ts
Hi, it's a simple implementation to allow custom gcode to disable the extruder. Using Klipper, M18 would disable all steppers, ignoring arguments.
At first I had added a "klipper support" checkbox into Settings, however I then chose to implement it just like the babystepping option, for the sake of consistency and flexibility. So I added a 'disableExtruderGCode' key, changable in the config.json (default value is 'M18 E'). For Klipper I use "SET_STEPPER_ENABLE STEPPER=extruder ENABLE=0", I can confirm it works (tried @pause and M0/M1).
Just a note. I had to downgrade electron-store to 6 (can't read config.json otherwise) and electron to 9 ("tilted" display otherwise) to get interface working (even before my changes, on clean setup). Of course I reverted dependencies to original values …
> Add klipper support for changing filament

- docs/index.html
Update scripts urls in docs files
Fixes #1584
> Update scripts urls in docs files

- src/app/app.component.ts
- src/app/app.service.ts
- src/app/services/socket/socket.octoprint.service.ts
> fix websocket and config upgrade bug

- angular.json
remove lottie warning when building
```
Warning: octodash/src/app/app.module.ts depends on 'lottie-web'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
> fix lottie warning

- helper/config.schema.js
- src/app/app.service.ts
- src/app/config/config.default.ts
- src/app/config/config.model.ts
- src/app/config/config.service.ts
- src/app/print-control/print-control.component.html
- src/app/services/printer/printer.octoprint.service.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/settings/settings.component.ts
Fixes #1618
Closes #1662
Fixes #1675
Closes #1098
> fix settings, feedrate, add axis inversion

- src/app/height-progress/height-progress.component.html
This class references the total height as was possible by themes in version 2.1.1 (allows fixing the NOX and Focus themes).
@pciavald this class was missing when you converted the layer-progress component to the height-progress component. 
This will facilitate closing of #1749
> Re-Added class: Height-progress - total

- themes/theGarbz/Focus/README.md
- themes/theGarbz/Focus/custom-styles.css
To revert the design to the previous one an additional
class is required for the height-progress to match the
old layer-progress setup. This will be subject to a 
separate pull request. 
Related to #1749 but does not fix the NOX theme.
> A temporary fix to the Layer Progress indication.

- themes/theGarbz/BigFingers/README.md
- themes/theGarbz/BigFingers/custom-styles.css
- themes/theGarbz/Focus/README.md
- themes/theGarbz/Focus/custom-styles.css
- themes/theGarbz/Glanceable/README.md
- themes/theGarbz/Glanceable/custom-styles.css
All themes updated to suit Layer Progress changes
Additional tweaking to vertical scroll bar height on some themes.
Removed additional by-line as it broke on some themes and isn't part of any upstream checks.
> Update to all Garbz Themes to suit 2.2.0

- src/app/job-status/job-status.component.html
> show no job running after print again (no touch)

- src/app/model/octoprint/plugins/enclosure.model.ts
- src/app/services/enclosure/enclosure.octoprint.service.ts
- src/app/services/enclosure/enclosure.service.ts
This adds back-end support for PWM outputs to the `EnclosureService`.
Please also consider enclosure plug-in PWM outputs while working on #1846.
> Support PWM Outputs of Enclosure Plug-In

- angular.json
- src/app/control/custom-actions/custom-actions.component.ts
- src/app/services/enclosure/enclosure.octoprint.service.ts
- src/app/services/enclosure/enclosure.service.ts
> add output actions

- src/app/config/config.service.ts
- src/app/files/files.component.html
- src/app/files/files.component.ts
- src/app/settings/settings.component.html
> automatically save file saving order

- scripts/install.sh
possible fix for recent install errors, #2206, #2207
> --allow-releaseinfo-change

- src/app/app.service.ts
- src/app/bottom-bar/bottom-bar.component.ts
- src/app/config/setup/personalization/personalization.service.ts
- src/app/config/setup/plugins/plugins.component.html
- src/app/config/setup/plugins/plugins.component.ts
- src/app/config/setup/setup.component.html
- src/app/config/setup/setup.component.ts
- Printer name not being loaded
- v2.2.0 setup migration not working
- Add Spool Manager to initial plugin selection
- Temperature not being shown after setup completed
> Fix various issues with the initial setup

- src/app/bottom-bar/bottom-bar.component.html
- src/app/bottom-bar/bottom-bar.component.ts
- src/app/notification/notification.service.ts
- src/app/services/socket/socket.octoprint.service.ts
- src/app/services/socket/socket.service.ts
printer info notification are now just shown in the bottom right and won't trigger a notification anymore
should fix #2720
> fix annoying notifications

- src/app/services/files/files.octoprint.service.ts
Switch file list to use display property instead of name for SD Card long filename support (EXTENDED_M20)
> SD Card Long Filename Support

- src/app/model/index.ts
- src/app/model/util-test.model.ts
- src/app/services/system/system.octoprint.service.ts
- src/app/services/system/system.service.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.ts
I was looking for this option in OctoDash today and realized it wasn't in there. Hope you don't mind me adding it! Let me know if you have any suggestions.
_Side note: I had a difficult time getting the project to run locally. I kept receiving errors about CommonJS and Electron. On my local machine, I just went ahead and converted everything to use modules instead in order to work around this issue. I'm not sure if Dependabot just updated things to the point where CommonJS isn't supported anymore or what 🤷‍♂️_
> Add local IP address to About screen: Resolves #622, #1202, #1320, #4128

- helper/discover.js
- src/app/config/setup/discover-octoprint/discover-octoprint.component.html
- src/app/config/setup/discover-octoprint/discover-octoprint.component.scss
- src/app/config/setup/discover-octoprint/discover-octoprint.component.ts
This PR fixes version comparison when checking if OctoPrint is at the minimum version.  This also adds better UI indications when an upgrade is required.
> Fix version comparison

- helper/config.schema.js
- src/app/app.service.ts
- src/app/config/config.default.ts
- src/app/config/config.model.ts
- src/app/config/config.service.ts
- src/app/files/files.component.ts
- src/app/settings/settings.component.html
This eliminates the need to select `sdcard` or `local` every time, and if you keep your files in some deeper path for whatever reason this helps with that too.
> Allow customizing of the default directory used in the file browser

- scripts/install.sh
Fixes #4071.  Since CORS is a requirement for OctoPrint now, it doesn't make sense to give the option to _not_ enable it.
> Don't ask if CORS should be enabled

- package.json
Without this packaged builds were broken
> Include the new helpers dir in packaged build

- src/app/app.service.ts
- src/app/settings/settings.component.html
- src/locale/messages.de.xlf
- src/locale/messages.fr.xlf
- src/locale/messages.xlf
In v2.4.0, the update checker logic was tweaked to use tag names.  This PR updates the logic to snag the release name again for display purposes.
> Display release title

- README.md
- src/app/settings/settings.component.html
- src/app/update/update.component.html
- src/app/update/update.component.ts
- src/helper/listener.js
- src/helper/update.js
- src/locale/messages.de.xlf
- src/locale/messages.fr.xlf
- src/locale/messages.xlf
This PR performs a few updates to the update procedure and documentation:
- Adds a section about updating to the readme (fixes #4860)
- Restarts _OctoDash,_ not OctoPrint's host system, after updates (fixes #4856)
- Allows a user to update OctoDash even if no update is available
> Improve update flow and docs

- src/app/settings/settings.component.ts
- src/locale/messages.xlf
This allows the config screen to load with fewer than six custom actions configured. While the UI doesn't allow for getting into that state, the companion plugin does (plus of course directly modifying the config is possible).
Fixes #4836
> Fix config for < 6 custom actions

- src/components/app.component.ts
Looks like this method got inadvertently deleted
> Fix toggle switch animation cache

- scripts/install.sh
> Fix autoboot setup process on Debian 12 / OctoPi 1.1.0

- src/components/action-center/action-center.component.ts
- src/locale/messages.da.xlf
- src/locale/messages.de.xlf
- src/locale/messages.fr.xlf
- src/locale/messages.xlf
- src/services/printer/printer.octoprint.service.ts
Fixes #4289
Each custom action can contain multiple commands, separated by `;`. When multiple gcode commands are present, each is sent as a separate API call to OctoPrint. This can result in OctoPrint processing those commands out of order. 
This change remedies that by sending all gcode in a custom action as a single request to OctoPrint, guaranteeing that those will be executed in order. This change also processes any special commands before sending the gcode, although I expect that will not cause any significant issues as commands are always dispatched without waiting for results, so the exact order of execution has always been undefined and variable.
> Send gcode from custom actions in batches

- src/locale/messages.xlf
- src/services/files/files.octoprint.service.ts
Print files with `#`, `-` and other characters were causing related API calls to fail, preventing such files from being viewed or started from OctoDash. This change adds URI encoding to those filenames when including in API calls to fix the issues.
> URI Encode filepaths in API calls

- CHANGELOG.md
- package-lock.json
- package.json
2.6.1 didn't get included, and 2.6.0 was still named 2.5.4
> Fix changelog for 2.6.0 and 2.6.1

- .github/workflows/build.yaml
Seems only `.yml` are produced. Also skips saving those in the GHA artifact for good measure
> Don't include `.yaml` in release

- .github/workflows/approve-and-merge-dependency-updates.yaml
The process of cutting a release branch, doing prerelease builds, and then deploying the release gets complicated when `main` is getting updated under the hood automatically
> Disable automerge of dependabot PRs
