src/app/app.component.html, src/app/app.component.ts, src/app/bottom-bar/bottom-bar.component.ts, src/app/display-layer-progress.service.spec.ts, src/app/display-layer-progress.service.ts, src/app/job-status.service.ts, src/app/job-status/job-status.component.ts, src/app/layer-progress/layer-progress.component.ts, src/app/printer-status.service.ts, src/app/printer-status/printer-status.component.ts
API implemented. Screen is now fully working, except DHT22 sensor. Closes #20.
=> Display layer progress api

src/app/layer-progress/layer-progress.component.ts, src/app/layer-progress/layer-progress.service.ts, src/app/printer-status/printer-status.component.ts
=> Fix double percentage character

src/app/job-status/job-status.service.ts, src/app/layer-progress/layer-progress.service.ts, src/app/octoprintAPI/jobAPI.ts, src/app/octoprintAPI/layerProgressAPI.ts, src/app/octoprintAPI/printerStatusAPI.ts, src/app/printer-status/printer-status.service.ts
=> Introduce interfaces for Octorprint API

src/app/app.module.ts, src/app/control/control.component.html, src/app/control/control.component.scss, src/app/control/control.component.ts, src/app/url.pipe.ts
=> Open iFrame from Custom Actions

src/app/job-status/job-status.component.ts, src/app/notification/notification.service.ts
Also errors are now shown again.
Closes #184
=> Clear loaded File after printing started

main.js, src/app/app.service.ts, src/app/main-menu/main-menu.component.html, src/app/main-menu/main-menu.component.scss, src/index.html
=> Version Update Notification now working again

src/app/printer-status/printer-status.component.scss
=> Fix Layout getting funky, if bed temperature is over a 100 degree

src/app/printer-status/printer-status.component.scss
=> Fixed on 1024x600

src/app/files/files.component.ts
=> Fixed Can't load file shown on initial loading

src/app/main-screen/main-screen.component.ts
=> Fixed Control View getting hidden while paused

package.json, src/app/octoprint-api/printerStatusAPI.ts, src/app/printer.service.ts
=> Fix issue with no heated bed

src/app/app.service.ts, src/app/config/config.service.ts, src/app/config/no-config/no-config.component.html, src/app/config/no-config/no-config.component.ts, src/app/job-status/job-status.component.html, src/app/job-status/job-status.component.ts, src/app/job.service.ts, src/app/main-screen/main-screen.component.html, src/app/main-screen/main-screen.component.ts, src/app/plugin-service/enclosure.service.ts
=> Integrate new Enclosure API

src/app/app.service.ts, src/app/files.service.ts, src/app/job-status/job-status.component.html, src/app/job.service.ts
=> Fix filament calculations with multiple tools

src/app/plugin-service/layer-progress.service.ts, src/app/settings/settings.component.scss, src/assets/reset.css
=> Don't use hardcoded layer offset

main.js, src/app/standby/standby.component.ts
=> DPMS getting correctly disabled

src/app/files.service.ts, src/app/files/files.component.html, src/app/octoprint-api/filesAPI.ts
Changes necessary to support both PrusaSlicerThumbnails and UltimakerFormatPackage plugin's extracted thumbnails, resolves #566
=> Additional Thumbnail Support

README.md, main.js, src/app/app.service.ts
=> Custom CSS

src/app/layer-progress/layer-progress.component.html
With that addition nothing changes, but gives the ability to also style the total layers number.
=> Add class to total layers number

src/app/filament/filament.component.html
=> Filament Screen UI Consistency

src/app/files/files.component.scss
=> prevent breadcrumbs in multiple lines

src/styles.scss
=> Prevent more touch drag events

src/app/app.service.ts, src/app/config/config.service.ts, src/app/config/no-config/no-config.component.ts, src/app/print-control/print-control.component.ts, src/app/settings/settings.component.html
=> customizable babystep gcode

angular.json, package-lock.json, package.json, scripts/install.sh
- install script now doesn't require an octoprint instance anymore
Closes #1055.
#1062.
=> Fix slow touch response and update install script

helper/listener.js
=> Don't blank after saving settings

src/app/app.component.html, src/app/app.component.ts, src/app/config/no-config/no-config.component.html, src/app/config/no-config/no-config.component.scss, src/app/config/no-config/no-config.component.ts, src/app/job.service.ts, src/app/octoprint-script.service.ts, src/app/print-control/print-control.component.html, src/app/print-control/print-control.component.scss, src/app/print-control/print-control.component.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.scss
Also improved loading of script.
Closes #1038.
Closes #939.
=> Restart + filament button added to pause screen

src/app/update/update.component.html
=> Use correct version string during update

src/app/app.service.ts, src/app/config/config.service.ts, src/app/config/no-config/no-config.component.ts, src/app/control/control.component.scss, src/app/files/files.component.scss, src/app/job-status/job-status.component.html, src/app/job-status/job-status.component.scss, src/app/job-status/job-status.component.ts, src/app/main-menu/main-menu.component.ts, src/app/print-control/print-control.component.html, src/app/print-control/print-control.component.scss, src/app/print-control/print-control.component.ts, src/app/printer-status/printer-status.component.scss, src/app/settings/settings.component.html, src/app/settings/settings.component.scss, src/app/settings/settings.component.ts, src/styles.scss, themes/NOX/README.md, themes/NOX/custom-styles.css
=> New Preview design while printing

src/app/job.service.ts
=> Use OctoPrint completion over self-calculated percentage

src/app/app.component.html, src/app/config/no-config/no-config.component.html, src/app/control/control.component.scss, src/app/filament/filament.component.html, src/app/files/files.component.html, src/app/files/files.component.scss, src/app/job-status/job-status.component.html, src/app/print-control/print-control.component.scss, src/app/printer-status/printer-status.component.scss, src/app/settings/settings.component.scss, src/app/standby/standby.component.html, src/app/update/update.component.html, src/styles.scss
=> remove backdrop filter and add dot animation

src/app/app.component.html, src/app/app.component.ts, src/app/config/no-config/no-config.component.ts, src/app/files.service.ts, src/app/octoprint-script.service.ts, src/styles.scss
=> improved script loading

src/app/files/files.component.html, src/app/files/files.component.scss, src/app/main-menu/main-menu.component.scss
=> increase settings touchbox size

.gitignore, angular.json, package-lock.json, package.json, src/app/filament/filament.component.ts
=> Remember last nozzle temperature during filament change

scripts/install.sh, scripts/update.sh
This is part of the fix for BR https://github.com/UnchartedBull/OctoDash/issues/1189. I'm not exactly sure where the code is for the application when checking for updates.
=> Added ARM64, AMD64, and ARMHF support to update.sh

helper/update.js
=> map arch to electron name

src/app/files.service.ts, src/app/files/files.component.html
=> replace folder files info with size info

helper/listener.js, main.js, package-lock.json, src/app/app.service.ts, src/app/config/config.default.ts, src/app/config/config.model.ts, src/app/config/config.schema.ts, src/app/config/config.service.ts
=> Make screen sleep & wakeup command configurable

themes/NOX/README.md, themes/NOX/custom-styles.css
See Issue https://github.com/UnchartedBull/OctoDash/issues/1389
=> Fix file loaded screen

scripts/install.sh
Added support for console autologin, so it no longer needs to be done manually.
=> Update install.sh to add autoconsole login, so it no longer is a manual step.

src/app/files/files.component.html, src/app/files/files.component.ts, src/app/services/files/files.octoprint.service.ts, src/app/services/socket/socket.octoprint.service.ts
=> Fix file sorting, loading animation & preview

.gitignore
avoid pushing yarn.lock by mistake as this repo's pkg manager is npm
=> ignore yarn.lock

src/app/print-control/print-control.component.ts
send M500 after setting babysetpZ to save the setting across printer reboots
Fixes #1293
=> save babystepZ to eeprom

themes/NOX/README.md, themes/NOX/custom-styles.css
Fix for NOX theme for OctoDash v2.2.0
Related issue: https://github.com/UnchartedBull/OctoDash/issues/1749
=> Fix for NOX theme for OctoDash v2.2.0

package-lock.json, package.json, src/app/filament/change-filament/change-filament.component.html, src/app/filament/choose-filament/choose-filament.component.html, src/app/filament/heat-nozzle/heat-nozzle.component.html, src/app/filament/move-filament/move-filament.component.html, src/app/filament/purge-filament/purge-filament.component.html
=> fix filament screens misalignment

src/app/control/control.component.html, themes/square/custom-styles.css
=> don't show back text in control screen (square theme)

angular.json, src/app/control/control.component.html, src/app/control/control.component.ts, src/app/files/files.component.html, src/app/files/files.component.scss, src/app/files/files.component.ts, src/app/printer-status/printer-status.component.html, src/app/printer-status/printer-status.component.scss, src/app/printer-status/printer-status.component.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.ts, src/styles.scss
=> close popovers with backdrop

src/app/services/socket/socket.octoprint.service.ts
@jneilliii did you open a bug ticket for this? Wasn't able to find one, if not please comment here, whether that fixes your problem with the printer not switching to the printing screen consistently.
=> Fix printing screen not shown

src/app/services/socket/socket.octoprint.service.ts, src/app/services/system/system.octoprint.service.ts
=> Show unauthorized error

src/app/app.component.html, src/app/app.component.scss, src/app/notification-center/notification-center.component.scss
=> Increase notification center icon hitbox

.github/workflows/build.yaml, .github/workflows/manual.yml
Update some of the actions used in workflows
=> Upgrade build actions

docs/index.html, src/app/settings/settings.component.html
A small little thing to give credit to the various contributors who have also worked on OctoDash!
=> Update copyright notice

src/app/app.component.html, src/app/app.module.ts, src/app/main-menu/main-menu.component.html, src/app/main-menu/main-menu.component.scss, src/app/main-menu/main-menu.component.ts, src/app/settings/settings-icon/settings-icon.component.html, src/app/settings/settings-icon/settings-icon.component.scss, src/app/settings/settings-icon/settings-icon.component.ts, src/app/standby/standby.component.html, src/app/update/update.component.html
This PR adds the settings icon to the standby and initialization screens as well, allowing access to the settings from any screen the user may need it.
=> Display settings icon on all main screens

src/app/update/update.component.scss, src/app/update/update.component.ts
This PR updates the bouncing progress bar to use CSS animations rather than JavaScript, providing a performance improvement and easier adjustments.
=> Use CSS animations for bouncing progress bar

helper/config.js, helper/listener.js, src/app/app.module.ts, src/app/reset/reset.component.html, src/app/reset/reset.component.scss, src/app/reset/reset.component.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.scss, src/app/settings/settings.component.ts
This PR adds an option to reset the configuration of OctoDash, so that a user may start from scratch if they so choose.
=> Add an option to reset the configuration

scripts/install.sh, scripts/update.sh
This PR improves the install and update scripts.  This includes changes from both #4152 and https://github.com/UnchartedBull/OctoDash/pull/3375/commits/90e80ab17754fd55a873c38ed1a45623008518cf.
=> Improve install and update scripts

CONTRIBUTING.md, helper/locale.js, main.js, package.json, src/app/app.service.ts, src/app/config/setup/welcome/welcome.component.html, src/app/settings/settings.component.html
This PR performs a number of updates to improve the experience for contributors:
- Update the contributing guidelines
- Place locale backups into their own folder
- Use an environment variable for dev env
- Scrap "big" mode since window size can be updated
- Don't prompt for updates in dev environment
=> Various updates for contributors

src/app/app.service.ts
This PR adds a notification whenever an update is available.
Note: relies on #4780.
=> Send a notification when an update is available

package-lock.json, package.json
This reverts commit ec443f809b2ca55b914d21328339ce75a2da5781.  See #4768 for more details.
=> Revert "Bump electron-store from 8.2.0 to 10.0.1 (#4799)"

src/app/settings/settings.component.html, src/locale/messages.de.xlf, src/locale/messages.fr.xlf, src/locale/messages.xlf
This PR updates the locale files and fixes a message with varying whitespace.
=> Update locale files and fix "duplicate" message

main.js, package-lock.json, package.json
This PR updates Electron to the latest version.  Additionally, this fixes the rendering issue with Electron v27+ on Raspberry Pi devices.
=> Upgrade Electron to latest version

src/app/services/printer/printer.octoprint.service.ts
=> Fix version comparison when handling dev versions

src/app/filament/filament.component.ts
I'm not sure how this worked before but seems like the easy fix
=> Properly skip tool selection for singletool

src/app/app.service.ts, src/locale/messages.xlf
Add a config migration for the Tuya plugin. I think we both made this fix on our forks but it got missed when merging everything upstream 🤷‍♂️
=> Migrate tuya plugin config

src/app/control/control.component.html, src/app/control/control.component.scss
This updates the control page to use different icons to better clarify the meaning (particularly for the extruder controls).
=> Use different icons for control page

src/app/filament/move-filament/move-filament.component.ts, src/locale/messages.xlf
This PR fixes a bug with filament changing (reported in https://github.com/UnchartedBull/OctoDash/issues/4847#issuecomment-2741563094).
=> Ensure filament changing always uses the selected tool

src/app/control/custom-actions/custom-actions.component.html, src/app/control/custom-actions/custom-actions.component.scss, src/app/control/custom-actions/custom-actions.component.ts
=> Fix `[!WEB]` command

src/app/main-screen/printer-status/printer-status.component.html
=> Fix text size for shared nozzle

angular.json, package.json, src/helper/locale.js, src/locale/messages.da.xlf, src/locale/messages.xlf
Made some changes to package.json so that "prepare" and "locale:update:all" works on Windows.
Also changed a little in src/helper/locale.js so that : gets removed (Windows isn't happy about those in filenames).
And finally I did the translation to Danish.
=> Add Danish i18n

src/locale/messages.da.xlf, src/locale/messages.de.xlf, src/locale/messages.fr.xlf
This PR updates the locale files and cleans up a few outstanding formatting issues.
Additionally, this PR fills in the blanks in the localization using machine translation (DeepL).
=> Update locale files

package-lock.json, package.json, src/locale/messages.xlf, src/services/app.service.ts
This PR fixes the config migration, following a slightly accidental change in #4871.  Fixes #5093.
=> Fix configuration migration for PSU based plugins

src/components/control/control.component.html
Fixes a bug that was seen in a user screenshot.
=> Fix extruder icon saying "false" on single extruder setting

src/services/app.service.ts
Follow-up to #5095 which didn't actually fix the migration.  Fixes #5109.
=> Fix configuration migration for plugins

package-lock.json, package.json
Actually bump the version in `package.json` so it's done properly. Really need to just automate these releases...
=> Create version 2.6.1
